image: markhobson/maven-chrome:jdk-11

cache:
  paths:
    - acceptance-tests/target

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn clean install -Dapp_env=dev -Dbrowser=ChromeHeadless